version: '3'

services:
  mysql:
    platform: 'linux/amd64'
    container_name: mysql
    build: ./
    hostname: mysql
    ports:
      - "3306:3306"
    env_file:
      - ./env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    volumes:
      - "./initDB:/docker-entrypoint-initdb.d"